### ISSUE TITLE
Update npmjs package from 0.0.4 to 0.1.3

### ISSUE THREAD

**Issue by kfarr** [theworkers/connect-favicons#2]
Thanks for accepting pull request. FYI it appears the npm module is outdated -- [npmjs listing](https://www.npmjs.com/package/connect-favicons) shows 0.0.4 but this repo is 0.1.3

**Comment by tmslnz** [comment]
Yup I know… I’ll need to get around resuming updates to NPM!
Sure you know already, but you could add the package via git url too if you don’t want to wait or depend on my pushing the updated version to NPM.

**Comment by kfarr** [comment]
Thanks will check that out!

**Comment by tmslnz** [comment]
The package is updated on NPM
